#include "Schedule/Domain/Model/RepeatScheduleAccessToken.h"
#include "Schedule/Model/Cache/RepeatSchedule.h"
#include "Schedule/Request/GetEventRequest.h"

namespace Gs2::Schedule::Domain::Model
{
    using Gs2::Schedule::Model::Cache::FRepeatScheduleCache;
    FRepeatScheduleAccessTokenDomain::FRepeatScheduleAccessTokenDomain(const Core::Domain::FGs2Ptr& Gs2, const Schedule::Domain::FGs2ScheduleDomainPtr& Service, TOptional<FString> NamespaceName, const Gs2::Auth::Model::FAccessTokenPtr& AccessToken, TOptional<FString> EventName, TOptional<bool> InSchedule): Gs2(Gs2), Service(Service), Client(MakeShared<Gs2::Schedule::FGs2ScheduleRestClient>(Gs2->RestSession)), ParentKey(Gs2::Schedule::Model::Cache::FRepeatScheduleCache::CreateCacheParentKey(NamespaceName, AccessToken.IsValid() ? AccessToken->GetUserId() : TOptional<FString>(), InSchedule.Get(true), AccessToken.IsValid() ? AccessToken->GetTimeOffset() : TOptional<int32>())), NamespaceName(NamespaceName), AccessToken(AccessToken), EventName(EventName), InSchedule(InSchedule) {}
    FRepeatScheduleAccessTokenDomain::FRepeatScheduleAccessTokenDomain(const FRepeatScheduleAccessTokenDomain& From): Gs2(From.Gs2), Service(From.Service), Client(From.Client), ParentKey(From.ParentKey), NamespaceName(From.NamespaceName), AccessToken(From.AccessToken), EventName(From.EventName), InSchedule(From.InSchedule) {}
    FRepeatScheduleAccessTokenDomain::FModelTask::FModelTask(const TSharedPtr<FRepeatScheduleAccessTokenDomain>& Self): Self(Self) {}
    FRepeatScheduleAccessTokenDomain::FModelTask::FModelTask(const FModelTask& From): TGs2Future(From), Self(From.Self) {}
    Gs2::Core::Model::FGs2ErrorPtr FRepeatScheduleAccessTokenDomain::FModelTask::Action(TSharedPtr<TSharedPtr<Schedule::Model::FRepeatSchedule>> Result)
    {
        const auto User = Self->AccessToken.IsValid() ? Self->UserId() : TOptional<FString>(); const auto Offset = Self->AccessToken.IsValid() ? Self->AccessToken->GetTimeOffset() : TOptional<int32>(); const auto Parent = FRepeatScheduleCache::CreateCacheParentKey(Self->NamespaceName, User, Self->InSchedule.Get(true), Offset); const auto Key = FRepeatScheduleCache::CreateCacheKey(Self->EventName);
        return Self->Gs2->Cache->ExecuteWithKeyLock(Schedule::Model::FRepeatSchedule::TypeName, Parent, Key, [this, Result]() {
            Schedule::Model::FRepeatSchedulePtr Value; const auto User = Self->AccessToken.IsValid() ? Self->UserId() : TOptional<FString>(); const auto Offset = Self->AccessToken.IsValid() ? Self->AccessToken->GetTimeOffset() : TOptional<int32>();
            if (FRepeatScheduleCache::TryGet(Self->Gs2->Cache, Self->NamespaceName, User, Self->InSchedule.Get(true), Self->EventName, Offset, &Value)) { *Result = Value; return Gs2::Core::Model::FGs2ErrorPtr(); }
            const auto Error = FRepeatScheduleCache::Fetch(Self->Gs2->Cache, Self->NamespaceName, User, Self->InSchedule.Get(true), Self->EventName, Offset, [Self = Self](Schedule::Model::FRepeatSchedulePtr* Out) {
                const auto Request = MakeShared<Schedule::Request::FGetEventRequest>()->WithContextStack(Self->Gs2->DefaultContextStack)->WithNamespaceName(Self->NamespaceName)->WithEventName(Self->EventName)->WithIsInSchedule(Self->InSchedule)->WithAccessToken(Self->AccessToken.IsValid() ? Self->AccessToken->GetToken() : FString());
                const auto Future = Self->Client->GetEvent(Request); Future->StartSynchronousTask(); if (Future->GetTask().IsError()) { const auto Error = Future->GetTask().Error(); Future->EnsureCompletion(); return Error; } const auto Event = Future->GetTask().Result(); Future->EnsureCompletion(); *Out = Event.IsValid() ? Event->GetRepeatSchedule() : nullptr; return Gs2::Core::Model::FGs2ErrorPtr();
            }, &Value); if (Error.IsValid()) return Error; *Result = Value; return Gs2::Core::Model::FGs2ErrorPtr();
        });
    }
    TSharedPtr<FAsyncTask<FRepeatScheduleAccessTokenDomain::FModelTask>> FRepeatScheduleAccessTokenDomain::Model() { return Gs2::Core::Util::New<FAsyncTask<FModelTask>>(this->AsShared()); }
    FRepeatScheduleAccessTokenDomain::FSubscribeWithInitialCallTask::FSubscribeWithInitialCallTask(const TSharedPtr<FRepeatScheduleAccessTokenDomain>& Self, const TFunction<void(Schedule::Model::FRepeatSchedulePtr)>& Callback): Self(Self), Callback(Callback) {}
    FRepeatScheduleAccessTokenDomain::FSubscribeWithInitialCallTask::FSubscribeWithInitialCallTask(const FSubscribeWithInitialCallTask& From): TGs2Future(From), Self(From.Self), Callback(From.Callback) {}
    Gs2::Core::Model::FGs2ErrorPtr FRepeatScheduleAccessTokenDomain::FSubscribeWithInitialCallTask::Action(TSharedPtr<TSharedPtr<Gs2::Core::Domain::CallbackID>> Result) { const auto Future = Self->Model(); Future->StartSynchronousTask(); Future->EnsureCompletion(); if (Future->GetTask().IsError()) return Future->GetTask().Error(); const auto Item = Future->GetTask().Result(); const auto Id = Self->Subscribe(Callback); Callback(Item); *Result = MakeShared<Gs2::Core::Domain::CallbackID>(Id); return nullptr; }
    TSharedPtr<FAsyncTask<FRepeatScheduleAccessTokenDomain::FSubscribeWithInitialCallTask>> FRepeatScheduleAccessTokenDomain::SubscribeWithInitialCall(TFunction<void(Schedule::Model::FRepeatSchedulePtr)> Callback) { return Gs2::Core::Util::New<FAsyncTask<FSubscribeWithInitialCallTask>>(this->AsShared(), Callback); }
    void FRepeatScheduleAccessTokenDomain::Invalidate() { const auto User = AccessToken.IsValid() ? UserId() : TOptional<FString>(); const auto Offset = AccessToken.IsValid() ? AccessToken->GetTimeOffset() : TOptional<int32>(); FRepeatScheduleCache::Delete(Gs2->Cache, NamespaceName, User, EventName, Offset); }
    Gs2::Core::Domain::CallbackID FRepeatScheduleAccessTokenDomain::Subscribe(TFunction<void(Schedule::Model::FRepeatSchedulePtr)> Callback)
    { const auto User = AccessToken.IsValid() ? UserId() : TOptional<FString>(); const auto Offset = AccessToken.IsValid() ? AccessToken->GetTimeOffset() : TOptional<int32>(); const auto Parent = FRepeatScheduleCache::CreateCacheParentKey(NamespaceName, User, InSchedule.Get(true), Offset); const auto Key = FRepeatScheduleCache::CreateCacheKey(EventName); const TWeakPtr<Gs2::Core::Domain::FGs2> WeakGs2 = Gs2; const TWeakPtr<Schedule::Domain::FGs2ScheduleDomain> WeakService = Service; const auto SourceToken = AccessToken; const auto RegisteredUser = User; const auto RegisteredOffset = Offset; const auto QueryNamespace = NamespaceName; const auto QueryEvent = EventName; const auto QuerySchedule = InSchedule; return Gs2->Cache->Subscribe(Schedule::Model::FRepeatSchedule::TypeName, Parent, Key, [Callback](TSharedPtr<FGs2Object> Object){ Callback(StaticCastSharedPtr<Schedule::Model::FRepeatSchedule>(Object)); }, [WeakGs2, WeakService, SourceToken, RegisteredUser, RegisteredOffset, QueryNamespace, QueryEvent, QuerySchedule](){ const auto Owner = WeakGs2.Pin(); const auto ServiceOwner = WeakService.Pin(); if (!Owner.IsValid() || !SourceToken.IsValid() || !RegisteredUser.IsSet() || !RegisteredOffset.IsSet()) return; const auto TokenSnapshot = MakeShared<Gs2::Auth::Model::FAccessToken>(*SourceToken); if (TokenSnapshot->GetUserId() != RegisteredUser || TokenSnapshot->GetTimeOffset() != RegisteredOffset) return; const auto Domain = MakeShared<FRepeatScheduleAccessTokenDomain>(Owner, ServiceOwner, QueryNamespace, TokenSnapshot, QueryEvent, QuerySchedule); const auto Task = Domain->Model(); Task->StartBackgroundTask(); }); }
    void FRepeatScheduleAccessTokenDomain::Unsubscribe(Gs2::Core::Domain::CallbackID CallbackID) { const auto User = AccessToken.IsValid() ? UserId() : TOptional<FString>(); const auto Offset = AccessToken.IsValid() ? AccessToken->GetTimeOffset() : TOptional<int32>(); Gs2->Cache->Unsubscribe(Schedule::Model::FRepeatSchedule::TypeName, FRepeatScheduleCache::CreateCacheParentKey(NamespaceName, User, InSchedule.Get(true), Offset), FRepeatScheduleCache::CreateCacheKey(EventName), CallbackID); }
}
